### ISSUE TITLE
Failure in Opera 12 - Cannot convert 'a' to object

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-js-client#121]
When running the fxa-content-server unit tests locally, this error is consistently reproduced:

> Cannot convert 'a' to object
<anonymous function: toBits>([arguments not available])@http://localhost:3030/bower_components/fxa-js-client/fxa-client.js:439
<anonymous function: unbundleKeyFetchResponse>([arguments not available])@http://localhost:3030/bower_components/fxa-js-client/fxa-client.js:1811
<anonymous function: FxAccountClient.prototype.accountKeys>([arguments not available])@http://localhost:3030/bower_components/fxa-js-client/fxa-client.js:2314
onSettled([arguments not available])@http://localhost:3030/bower_components/fxa-js-client/fxa-client.js:1317
flush([arguments not available])@http://localhost:3030/bower_components/fxa-js-client/fxa-client.js:1021
handleTimer([arguments not available])@http://localhost:3030/bower_components/fxa-js-client/fxa-client.js:1085

**Comment by vladikoff** [comment]
Opera 12 is dead :skull:
