### ISSUE TITLE
404 for `POST /undefined/v1/recovery_email/verify_code`

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-js-client#142]
Was looking at some Kibana logs of 404 on the content server and noticed this odd url that was 404:

`POST /undefined/v1/recovery_email/verify_code HTTP/1.1"`

There's quite a few of these and they don't appear to be tied to any particular browser version.

```
{
  "_source": {
    "Timestamp": "2015-01-21T09:26:09.440Z",
    "Type": "elb_upstream",
    "Logger": "FxaContentWebserver",
    "Severity": 7,
    "Payload": "",
    "EnvVersion": "",
    "Pid": 0,
    "Hostname": "ip-nnn-nnn-nnn-nnn",
    "upstream_response_time": 0.003,
    "http_x_forwarded_for": "",
    "http_referer": "https://accounts.firefox.com/verify_email?uid=xxxxx&code=xxxxx",
    "body_bytes_sent": 672,
    "user_agent_browser": "Chrome",
    "user_agent_os": "Android",
    "user_agent_version": 39,
    "request": "POST /undefined/v1/recovery_email/verify_code HTTP/1.1",                                                                    
    "request_time": 0.003,                                                                                                                  
    "status": 404                                                                                                                           
  },                                                                                                                                        
}     
```

In a rough look, it looks like the check here needs to guard against undefined
https://github.com/mozilla/fxa-js-client/blob/ec7b4bcd4e797dda2f7a3bac077af87f6ec0fa17/client/FxAccountClient.js#L37
Didn't trace back to where the caller of that is passing in an empty uri though.

**Comment by shane-tomlinson** [comment]
This is strange, the only way I have been able to get anything like this to happen is if I manually set the `"authServerUrl"` to the string `undefined`. If `authServerUrl` is set to the value `undefined`, then [the fxa-js-client](https://github.com/mozilla/fxa-content-server/blob/71aca8403cbfc717572303f793f131180a317617/app/scripts/lib/fxa-client.js#L41) is never created and a `client is undefined` error is shown when trying to interact with the auth server.

### Approaches tried (using the /signin page):
* Abort the XHR request to `/config` from the client - redirected to the 500 page.
* Prevent a response for `/config` - page is [blank](https://github.com/mozilla/fxa-content-server/issues/2060).
* Return an empty response - redirected to the 500 page.
* Return an empty string `res.send('')` - redirected to the 500 page.
* Return a JSON response of `{}` - page starts but a fxa-js-client is not created
* Return an empty JSON string `res.json('')` - same as `{}`
* Return a response w/o `authServerUrl` - same as `{}`
* Return invalid JSON `res.json('asdf')` - same as `{}`
* Throw an error in app-start.js->initializeConfig, initializeL10n, or initializeInterTabChannel - [page is blank](https://github.com/mozilla/fxa-content-server/issues/2061)
* Disable cookies - cookies disabled page is shown.
* Disable access to localStorage (set dom.storage.enabled = false) - cookies disabled page is shown.

### One approach that recreates problem
* Set `authServerUrl` to the string `'undefined'`

```diff
diff --git a/server/lib/routes/get-config.js b/server/lib/routes/get-config.js
index 41354f1..37b6785 100644
--- a/server/lib/routes/get-config.js
+++ b/server/lib/routes/get-config.js
@@ -65,7 +65,7 @@ module.exports = function (i18n) {
       // to see if cookies are enabled. If cookies are disabled,
       // the `__cookie_check` cookie will not arrive.
       cookiesEnabled: !!req.cookies['__cookie_check'],
-      authServerUrl: getAuthServerUrl(userAgent),
+      authServerUrl: 'undefined',
       oAuthUrl: getOAuthServerUrl(userAgent),
       profileUrl: getProfileServerUrl(userAgent),
       oAuthClientId: clientId,
```

**Comment by pdehaan** [comment]
@shane-tomlinson Is it possibly a timing issue with slow network where we're trying to send off a request before getting the results back from /config?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson Is it possibly a timing issue with slow network where we're trying to send off a request before getting the results back from /config?

@pdehaan - that was my initial hunch, so I tried to indefinitely delay the return from `/config`. https://github.com/mozilla/fxa-content-server/issues/2060 is the result. The content server just waits.. and waits.. and waits.

**Comment by pdehaan** [comment]
Heck, here's a few more random results from Kibana that show `undefined` in the request URL...

### 1. "GET /_undefined_/v1/session/status HTTP/1.1"
```json
{
  "_source": {
    "Timestamp": "2015-01-23T20:21:22.395Z",
    "http_x_forwarded_for": "",
    "http_referer": "https://accounts.firefox.com/settings",
    "body_bytes_sent": 761,
    "user_agent_browser": "Firefox",
    "user_agent_os": "Windows 7",
    "user_agent_version": 35,
    "request": "GET /undefined/v1/session/status HTTP/1.1",
    "request_time": 0.003,
    "status": 404
  }
}
```

### 2. "POST /_undefined_/v1/account/create?keys=true HTTP/1.1"
```json
{
  "_source": {
    "upstream_response_time": 0.003,
    "http_x_forwarded_for": "",
    "http_referer": "https://accounts.firefox.com/signup?service=sync&context=fx_desktop_v1",
    "body_bytes_sent": 660,
    "user_agent_browser": "Firefox",
    "user_agent_os": "Windows XP",
    "user_agent_version": 34,
    "request": "POST /undefined/v1/account/create?keys=true HTTP/1.1",
    "request_time": 0.003,
    "status": 404
  }
```

### 3. "POST /_undefined_/v1/password/forgot/send_code HTTP/1.1"
```json
{
  "_source": {
    "Timestamp": "2015-01-23T16:44:30.349Z",
    "upstream_response_time": 0.002,
    "http_x_forwarded_for": "",
    "http_referer": "https://accounts.firefox.com/reset_password",
    "body_bytes_sent": 657,
    "user_agent_browser": "Firefox",
    "user_agent_os": "Android",
    "user_agent_version": 35,
    "request": "POST /undefined/v1/password/forgot/send_code HTTP/1.1",
    "request_time": 0.002,
    "status": 404
  }
}
```

**Comment by shane-tomlinson** [comment]
@pdehaan, @jrgm, is this still a problem?

**Comment by vladikoff** [comment]
@shane-tomlinson yeah 

![](http://v14d.com/i/557760470c948.png)

**Comment by shane-tomlinson** [comment]
@vladikoff - thanks. This is less than awesome.

**Comment by shane-tomlinson** [comment]
My heart tells me this is a content server bug, I'm going to copy the issue over there and link to this.

**Comment by vladikoff** [comment]
Will patch this and add more tests....
