### ISSUE TITLE
accountLock tests always throw in account.js

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-js-client#166]
tests/lib/account.js does not seem to test for anything, as even with "account" being undefined, it does not throw an error.
@pdehaan 
@vladikoff 
@zaach 
@shane-tomlinson

**Comment by vladikoff** [comment]
It does work and test things, ,see where account is defined: https://github.com/mozilla/fxa-js-client/blob/master/tests/lib/account.js#L177 

However there are a few tests where we need to clean up the use of account

**Comment by vladikoff** [comment]
These tests should be fixed by setting a value https://github.com/mozilla/fxa-js-client/pull/164/files#r33523266

**Comment by vladikoff** [comment]
renamed the issue.

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/fxa-js-client/pull/164#discussion_r33523266

[./tests/lib/account.js#345-355](https://github.com/mozilla/fxa-js-client/blob/438b76fd13361bfb4d8eb599bdce8ccd51bdda85/tests/lib/account.js#L345-L355)

Note that `account` will likely be `undefined` on lines 347 and 353, so we'll probably throw an error when trying to access an undefined `account.input.password` and `account.input.email`.

**Comment by pdehaan** [comment]
@vladikoff Are you sure? I see that `account` is defined on line 177 in your link, but it should go out of scope on line 201 since the `var account;` is local to that `test()`. No?
