### ISSUE TITLE
xhr.status === 0 and xhr.status.503 w/o a body should be `service unavailable` errors

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-js-client#192]
These currently result in a [`timeout error`](https://github.com/mozilla/fxa-js-client/blob/5954e3df12720b6826b775099e8560219e4c3a6d/client/lib/request.js#L85:L87) which doesn't allow for great content server messaging.

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/3641
https://github.com/mozilla/fxa-content-server/issues/4240

**Comment by shane-tomlinson** [comment]
429 should be THROTTLED. If there is a response body that's not JSON, 429 should still be THROTTLED and 503 should still be SERVICE_UNAVAILABLE.

**Comment by vladikoff** [comment]
🗡 closing until needed
