### ISSUE TITLE
Tests are not capable of inspecting the fxa request

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-js-client#207]
In the tests for this repo, we do a lot of "if option x is set to y, assert the request doesn't fail". That's okay as a starting point but fails to catch a whole class of bugs.

We should also be able to do "if option x is set to y, assert that the request looks like z". Path, query parameters, payload, headers; we should be asserting all of that jazz.

**Comment by vladikoff** [comment]
If anyone needs to deep inspect the requests that the client is making then please use something like: 
https://github.com/mozilla/fxa-js-client/pull/217/files
