### ISSUE TITLE
Should missing required parameters reject rather than throw?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-js-client#244]
Functions that sometimes throw and sometimes resolve/reject are an anti-pattern. The `required` function that we use to check mandatory arguments throws and we don't call it inside a promise chain, so the thrown error is propagated to callers directly.

Obviously if callers themselves place one of these methods inside a promise chain then things work out okay, but that seems like a convoluted mechanism to impose on calling code. Better to always reject for errors imho, even those that originate from checking arguments in this lib.

**Comment by shane-tomlinson** [comment]
👍 to this. I never notice it on the content server side because all calls to the fxa-js-client are wrapped in promises.
