### ISSUE TITLE
Wrong User-Agent Header

### ISSUE THREAD

**Issue by Tobsic** [mozilla/fxa-js-client#245]
The User-Agent header needs to be a valid one for the fxa-api. In python [syncclient](github.com/mozilla-services/syncclient) it starts with "Mozilla/5.0 (Mobile; Firefox Accounts; rv:1.0)". I tested it and seems to work. xhr2 doesn't allow to set the User-Agent header (I opened a [issue](https://github.com/pwnall/node-xhr2/issues/29) for that).

**Comment by vladikoff** [comment]
Hey! What do you mean "valid user agent", what issue are you experiencing?

**Comment by rfk** [comment]
I expect it refers to failing this (private) check: https://github.com/mozilla/fxa-customs-server-private/blob/master/lib/server.js#L245

**Comment by Tobsic** [comment]
@vladikoff: I get this promise from the signIn
```
{ state: 'rejected',
  reason:
   { code: 400,
     errno: 125,
     error: 'Request blocked',
     message: 'The request was blocked for security reasons',
     info: 'https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format',
     verificationMethod: 'email-captcha',
     verificationReason: 'login' } }
```
I tested it with [node-fx-sync](https://github.com/zaach/node-fx-sync) and a modified version of it's [xhr](https://github.com/zaach/node-xmlhttprequest), that it sets the User-Agent to "Mozilla/5.0 (Mobile; Firefox Accounts; rv:1.0)". That works.
I think @rfk is right. (I can just see the [public version](https://github.com/mozilla/fxa-customs-server/blob/master/lib/server.js#L245) and not the extra checks)

**Comment by vladikoff** [comment]
No plans to fix this at this time
