### ISSUE TITLE
Better tests for this repo

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-js-client#259]
From what I've seen, the tests in this repo don't do a great job of asserting that the correct data is sent to the auth server. We do get some implied coverage on that front from the tests run against a real server, but really we should be asserting it directly.

I'd be in favour of a root-and-branch reappraisal of our testing approach in this repo, I wonder if we could squeeze such a thing into the Q4 OKRs. Adding a comment to the doc now.

**Comment by vladikoff** [comment]
Might help https://github.com/mozilla/fxa-js-client/issues/207#issuecomment-256948685

**Comment by vladikoff** [comment]
> If anyone needs to deep inspect the requests that the client is making then please use something like:
https://github.com/mozilla/fxa-js-client/pull/217/files
