### ISSUE TITLE
drop support for old browsers

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-js-client#264]
This repo still officially supports [Firefox 18 and IEs 9-11](https://github.com/mozilla/fxa-js-client/blob/5ff439433c1e4068e5476cd76685e743fc5a797a/tests/intern_sauce.js#L30). 

I propose we drop support for those old browsers and have the consumer of the library use babel if support is needed.

**Comment by vladikoff** [comment]
mostly done in https://github.com/mozilla/fxa-js-client/blob/master/tests/intern_sauce.js and with latest webpack migration
