### ISSUE TITLE
Has the fxa-js-client outlived its usefulness?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-js-client#268]
@rfk brought up to me today and I wondered just yesterday while wrangling tests. Has the fxa-js-client outlived its usefulness? The client was created as an abstraction for reliers to integrate with FxA. In reality, only the content-server makes use of the client, and it wraps every single public method so that it can load the client on demand.

Upsides of having the client:

1. It's a nice abstraction that can be tested independently.
2. Reliers like the browser could in theory make use of this abstraction (they have not up to this point, instead they have created their own clients).

Downsides of having the client:

1. Duplicate code for promise libraries and sjcl which is also included in the content-server.
2. Dependency management - any changes here need a release and a corresponding PR to the content server.
3. That big ugly wrapper in the content-server.

Who else can pile on?

**Comment by vladikoff** [comment]
> Upsides of having the client:

Another one: Devs use it to test things in Browser and Node

**Comment by vladikoff** [comment]
Years ago there was a plan to replace this https://github.com/mozilla/fxa-auth-server/blob/master/test/client/index.js with fxa-js-client

**Comment by vladikoff** [comment]
> Upsides of having the client:

Faster / less tests in fxa-content-server

**Comment by shane-tomlinson** [comment]
Add sinon spies to the local tests otherwise they don't do a whole bunch really.

Remote tests actually test things.

We're going to keep the client.

But we should do a mono-repo sometime.
